export enum EmployerType {
  SMALL_STARTUP = 'SMALL_STARTUP',
  MEDIUM_STARTUP = 'MEDIUM_STARTUP',
  LARGE_STARTUP = 'LARGE_STARTUP',
  INTERNATIONAL_NONTECH_CORP = 'INTERNATIONAL_NONTECH_CORP',
  INTERNATIONAL_TECH_CORP = 'INTERNATIONAL_TECH_CORP',
  ISRAELI_NONTECH_CORP = 'ISRAELI_NONTECH_CORP',
  ISRAELI_TECH_CORP = 'ISRAELI_TECH_CORP',
  DEFENSE_CORP = 'DEFENSE_CORP',
  OTHER = 'OTHER',
}
